"""
Solution for 389. Find the Difference
https://leetcode.com/problems/find-the-difference/
"""
from collections import Counter

class Solution:
    """
    Runtime: 36 ms, faster than 97.86% of Python3 online submissions for Find the Difference.
    Memory Usage: 13.3 MB, less than 13.13% of Python3 online submissions for Find the Difference.
    """
    def findTheDifference(self, s, t):
        """
        Given two strings s and t which consist of only lowercase letters.

        String t is generated by random shuffling string s and then add one more letter at a random
        position.

        Find the letter that was added in t.

        Example:

        Input:
        s = "abcd"
        t = "abcde"

        Output:
        e

        Explanation:
        'e' is the letter that was added.
        Args:
            s: str value to look the difference with
            t: str value which consists of random chars in s, with one additional char

        Returns:
            str: consists of one char which is the difference between s and t
        """
        s_counter = Counter(s)
        t_counter = Counter(t)

        for char in t_counter.keys():
            if not s_counter[char] == t_counter[char]:
                return char
